<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[<a href='file:///C:\Users\Kames\Desktop\Screenshots\passed/VerifyPageTitleTest.png'> <img src='file:///C:\Users\Kames\Desktop\Screenshots\passed/VerifyPageTitleTest.png' hight='550' width='649'/> </a>]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="73839" started-at="2018-03-03T15:28:24Z" finished-at="2018-03-03T15:29:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="73839" started-at="2018-03-03T15:28:24Z" finished-at="2018-03-03T15:29:37Z">
      <class name="Com.QA.TestCases.LoginTestCase">
        <test-method status="PASS" signature="setUp()[pri:0, instance:Com.QA.TestCases.LoginTestCase@2b9627bc]" name="setUp" is-config="true" duration-ms="68597" started-at="2018-03-03T15:28:24Z" finished-at="2018-03-03T15:29:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="VerifyPageTitleTest()[pri:1, instance:Com.QA.TestCases.LoginTestCase@2b9627bc]" name="VerifyPageTitleTest" duration-ms="18" started-at="2018-03-03T15:29:32Z" finished-at="2018-03-03T15:29:32Z">
          <reporter-output>
            <line>
              <![CDATA[<a href='file:///C:\Users\Kames\Desktop\Screenshots\passed/VerifyPageTitleTest.png'> <img src='file:///C:\Users\Kames\Desktop\Screenshots\passed/VerifyPageTitleTest.png' hight='550' width='649'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- VerifyPageTitleTest -->
        <test-method status="FAIL" signature="LoginTest()[pri:2, instance:Com.QA.TestCases.LoginTestCase@2b9627bc]" name="LoginTest" duration-ms="2608" started-at="2018-03-03T15:29:33Z" finished-at="2018-03-03T15:29:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Facbook – log in or sign up] but found [Log in to Facebook | Facebook]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Facbook – log in or sign up] but found [Log in to Facebook | Facebook]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Com.QA.TestCases.LoginTestCase.LoginTest(LoginTestCase.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="CloseMethod()[pri:0, instance:Com.QA.TestCases.LoginTestCase@2b9627bc]" name="CloseMethod" is-config="true" duration-ms="2152" started-at="2018-03-03T15:29:35Z" finished-at="2018-03-03T15:29:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseMethod -->
      </class> <!-- Com.QA.TestCases.LoginTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
